#!/bin/sh

cd /opt/hblink3 || exit 1

if [ "$PARROT_ENABLE" = "1" ]; then
    echo "Starting HBlink with Parrot....."
    python /opt/hblink3/bridge.py -c hblink.cfg -r rules.py &
else
    python /opt/hblink3/hblink.py -c hblink.cfg
fi
